name = "bitboard"
# Pin a compatibility date for Workers runtime
compatibility_date = "2024-09-01"
# Required by @cloudflare/next-on-pages
compatibility_flags = ["nodejs_compat"]

# Tell Pages where the built output lives (used to validate config and
# apply flags from this file). This silences the Pages warning.
pages_build_output_dir = ".vercel/output/static"

# Preview/Staging D1 binding (used by non-production deployments)
[[d1_databases]]
binding = "DB"
database_name = "bitsbarter-staging"
database_id = "d5ed8250-15da-4131-8b78-c364a40515f4"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "bitsbarter-prod"
database_id = "8c9de8f7-451b-4c90-b92c-5cd447907d46"

# If you later bind D1/KV/Queues/etc, add them here (example):
# [[d1_databases]]
# binding = "DB"
# database_name = "your-d1-name"
# database_id = "<uuid>"

