-- Enhanced staging database seeding for bitsbarter
-- This file seeds the staging database with realistic test data

-- Clear existing data (for clean seeding)
DELETE FROM listings;
DELETE FROM users;

-- Seed users with varied profiles
INSERT INTO users (id, email, username, sso, verified, created_at, image, rating, deals) VALUES
  ('user_satoshi', 'satoshi@example.com', 'satoshi', 'google', 1, strftime('%s','now') - 365*24*60*60, 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face', 4.9, 47),
  ('user_luna', 'luna@example.com', 'luna', 'google', 1, strftime('%s','now') - 300*24*60*60, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face', 4.7, 23),
  ('user_rob', 'rob@example.com', 'rob', 'google', 0, strftime('%s','now') - 250*24*60*60, 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face', 4.8, 31),
  ('user_mika', 'mika@example.com', 'mika', 'google', 1, strftime('%s','now') - 200*24*60*60, 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face', 4.6, 18),
  ('user_arya', 'arya@example.com', 'arya', 'google', 0, strftime('%s','now') - 180*24*60*60, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face', 4.5, 12),
  ('user_nova', 'nova@example.com', 'nova', 'google', 1, strftime('%s','now') - 150*24*60*60, 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face', 4.4, 9),
  ('user_kai', 'kai@example.com', 'kai', 'google', 0, strftime('%s','now') - 120*24*60*60, 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face', 4.3, 7),
  ('user_zen', 'zen@example.com', 'zen', 'google', 1, strftime('%s','now') - 100*24*60*60, 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face', 4.2, 5),
  ('user_olivia', 'olivia@example.com', 'olivia', 'google', 0, strftime('%s','now') - 80*24*60*60, 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face', 4.1, 3),
  ('user_noah', 'noah@example.com', 'noah', 'google', 1, strftime('%s','now') - 60*24*60*60, 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face', 4.0, 1);

-- Seed listings with enhanced descriptions and varied distribution per user
-- User: satoshi (7 listings) - Mining expert
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Antminer S19 Pro (110TH)', 'Professional-grade Bitcoin mining rig in excellent condition. This unit has been running in a climate-controlled environment with proper ventilation and maintenance. Includes original power supply unit (PSU) and all accessories. Hash rate consistently delivers 110TH/s with low power consumption. Perfect for serious miners or those looking to enter the mining space. Pickup preferred from Markham area, but can arrange delivery within GTA for additional fee. Cash in sats preferred, but will accept other payment methods. Unit has been cleaned and tested thoroughly before listing.', 'Mining Gear', 'sell', 'Markham, ON', 43.8561, -79.3370, 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=1200&auto=format&fit=crop', 14500000, 'user_satoshi', NULL, strftime('%s','now') - 365*24*60*60),
  ('4TB NVMe SSD', 'Brand new sealed Samsung 970 EVO Plus 4TB NVMe SSD. This is the latest generation with exceptional read/write speeds up to 3,500MB/s and 3,300MB/s respectively. Perfect for high-performance workstations, gaming rigs, or as a fast storage solution for your mining operations. Includes full warranty and original packaging. Price is firm as this is already significantly below retail. Meetup in Toronto area preferred, can also ship if buyer covers shipping costs.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop', 6000000, 'user_satoshi', NULL, strftime('%s','now') - 300*24*60*60),
  ('eBike Conversion Kit', 'Complete 500W electric bike conversion kit with everything you need to electrify your existing bicycle. Includes brushless hub motor, 36V 10.4Ah lithium battery, LCD controller, throttle, brake sensors, and all necessary wiring. Battery has excellent range (40-60km depending on terrain and assistance level). Kit is brand new, never installed. Perfect for commuters or recreational riders looking to add electric assist. Installation is straightforward for those with basic mechanical skills. Local pickup in Toronto area preferred.', 'Sports & Outdoors', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1605710344272-f7e222d1f4a1?w=1200&auto=format&fit=crop', 8000000, 'user_satoshi', NULL, strftime('%s','now') - 250*24*60*60),
  ('Smart Thermostat', 'Nest Learning Thermostat 3rd generation in excellent condition. This smart thermostat learns your schedule and automatically adjusts temperature for optimal comfort and energy savings. Features include WiFi connectivity, smartphone app control, energy usage reports, and compatibility with most HVAC systems. Includes wall plate and mounting hardware. Unit has been factory reset and is ready for new installation. Perfect for smart home enthusiasts or anyone looking to reduce heating/cooling costs. Local pickup preferred.', 'Home & Garden', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=1200&auto=format&fit=crop', 900000, 'user_satoshi', NULL, strftime('%s','now') - 200*24*60*60),
  ('NAS Hard Drive 8TB', 'Western Digital Red 8TB NAS hard drive with extremely low power-on hours. This drive is specifically designed for network-attached storage systems and offers excellent reliability for 24/7 operation. SMART status shows all parameters are excellent with no bad sectors. Perfect for expanding your home server, backup system, or mining operation storage. Drive has been tested thoroughly and comes with a detailed health report. Price is firm as this is already well below market value for a drive in this condition.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=1200&auto=format&fit=crop', 1600000, 'user_satoshi', NULL, strftime('%s','now') - 150*24*60*60),
  ('Bitcoin Mining Consultation', 'Professional Bitcoin mining consultation service for individuals and small businesses. Services include mining rig selection, setup and configuration, optimization for maximum efficiency, and ongoing maintenance support. I have over 5 years of experience in the mining space and can help you navigate the complexities of mining profitability, electricity costs, and hardware selection. Available for in-person consultation in GTA or remote sessions. Perfect for those new to mining or looking to optimize existing operations.', 'Services', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop', 2500000, 'user_satoshi', NULL, strftime('%s','now') - 100*24*60*60),
  ('Mining Rig Cooling System', 'Custom-built cooling system for Bitcoin mining rigs. Includes industrial-grade fans, ducting, and temperature monitoring equipment. System is designed to maintain optimal operating temperatures while minimizing noise. Perfect for home miners or small-scale operations. Includes installation instructions and can be customized for different rig configurations. Local pickup only due to size and weight. Price negotiable for serious buyers.', 'Mining Gear', 'sell', 'Markham, ON', 43.8561, -79.3370, 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?w=1200&auto=format&fit=crop', 1800000, 'user_satoshi', NULL, strftime('%s','now') - 50*24*60*60);

-- User: luna (6 listings) - Tech enthusiast
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Looking for: Ryzen 7 / 3070 build', 'WTB a clean 1440p gaming PC with Ryzen 7 processor and RTX 3070 graphics card. Prefer systems that have been well-maintained with no mining history. Looking for complete builds including case, power supply, and storage. Willing to pay premium for systems with quality components and clean cable management. Prefer local pickup in downtown Toronto area but will consider GTA for the right system. Budget is flexible for the right build. Please include detailed specs and photos when responding.', 'Electronics', 'want', 'Toronto, ON (Downtown)', 43.6510, -79.3810, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=1200&auto=format&fit=crop', 5200000, 'user_luna', NULL, strftime('%s','now') - 300*24*60*60),
  ('ThinkPad T14 Gen 3', 'Excellent condition ThinkPad T14 Gen 3 with Intel i7-1165G7 processor, 16GB RAM, and 512GB NVMe SSD. This business laptop has been lightly used and maintained in perfect condition. Features include fingerprint reader, backlit keyboard, and excellent battery life (still gets 8+ hours). Includes original charger and carrying case. Perfect for professionals, students, or anyone needing a reliable workhorse laptop. Price is firm as this is already well below market value. Local pickup in Mississauga preferred.', 'Electronics', 'sell', 'Mississauga, ON', 43.5890, -79.6441, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop', 15000000, 'user_luna', NULL, strftime('%s','now') - 280*24*60*60),
  ('3D Printer (Ender 3)', 'Ender 3 3D printer that has been extensively tuned and upgraded for optimal performance. Includes numerous upgrades: glass bed, upgraded extruder, silent stepper drivers, and custom firmware. Printer is calibrated and ready to print with excellent print quality. Perfect for makers, hobbyists, or anyone interested in 3D printing. Includes several spools of PLA filament and various printing accessories. Local pickup in Etobicoke area preferred. Price is negotiable for serious buyers.', 'Electronics', 'sell', 'Etobicoke, ON', 43.6205, -79.5132, 'https://images.unsplash.com/photo-1581093588401-16f8b8c9f7d9?w=1200&auto=format&fit=crop', 2500000, 'user_luna', NULL, strftime('%s','now') - 250*24*60*60),
  ('Cordless Drill Kit', 'DeWalt 20V MAX cordless drill and impact driver combo kit in excellent condition. Includes two 5.0Ah batteries, charger, and carrying case. Both tools have been lightly used and are in perfect working order. Perfect for DIY projects, home repairs, or professional use. Batteries hold excellent charge and tools have plenty of life left. Price is firm as this is already significantly below retail. Local pickup in Toronto area preferred.', 'Home & Garden', 'sell', 'Vaughan, ON', 43.8372, -79.5085, 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?w=1200&auto=format&fit=crop', 700000, 'user_luna', NULL, strftime('%s','now') - 200*24*60*60),
  ('Web Design Service', 'Professional web design service specializing in landing pages and small business websites. I create modern, responsive websites that convert visitors into customers. Services include custom design, mobile optimization, SEO basics, and content management system setup. Perfect for small businesses, startups, or individuals needing an online presence. Portfolio available upon request. Pricing is competitive and includes consultation, design, and basic training. Available for projects throughout GTA.', 'Services', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop', 1200000, 'user_luna', NULL, strftime('%s','now') - 150*24*60*60),
  ('Looking for: WiFi 6 Router', 'WTB a reliable WiFi 6 router with good range and performance. Looking for models like Asus RT-AX86U, TP-Link Archer AX6000, or similar. Must be in excellent condition with no issues. Router should support WiFi 6 (802.11ax) and have good coverage for a medium-sized home. Willing to pay fair market value for quality equipment. Local pickup preferred in Toronto area. Please include model number and condition when responding.', 'Electronics', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&auto=format&fit=crop', 500000, 'user_luna', NULL, strftime('%s','now') - 100*24*60*60);

-- User: rob (5 listings) - Service provider
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Bitcoin Node Setup Service', 'Professional Bitcoin node installation and configuration service. I help individuals and businesses set up and maintain their own Bitcoin nodes for enhanced privacy, security, and network contribution. Services include hardware selection, software installation, configuration optimization, and ongoing maintenance support. Perfect for Bitcoin enthusiasts, privacy-conscious users, or anyone wanting to support the network. Available for in-person setup in Vancouver area or remote consultation. Includes detailed documentation and training.', 'Services', 'sell', 'Vancouver, BC', 49.2827, -123.1207, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop', 500000, 'user_rob', NULL, strftime('%s','now') - 250*24*60*60),
  ('27" 4K Monitor', 'LG 27UK850-W 27-inch 4K IPS monitor in excellent condition. This professional-grade monitor features stunning color accuracy, HDR support, and USB-C connectivity. Perfect for photo/video editing, graphic design, or anyone needing precise color reproduction. Monitor has been calibrated and maintained in a smoke-free environment. Includes original stand and all cables. Price is firm as this is already well below retail. Local pickup in Toronto area preferred.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop', 3500000, 'user_rob', NULL, strftime('%s','now') - 220*24*60*60),
  ('Looking for: Bike Helmet M', 'WTB a clean and safe bike helmet in size Medium. Looking for reputable brands like Giro, Bell, or Specialized. Helmet must be in excellent condition with no damage or signs of impact. Safety is paramount, so only interested in helmets that meet current safety standards. Willing to pay fair market value for quality equipment. Local pickup preferred in Toronto area. Please include brand, model, and condition when responding.', 'Sports & Outdoors', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop', 100000, 'user_rob', NULL, strftime('%s','now') - 200*24*60*60),
  ('PC Cable Management Kit', 'Complete cable management solution for PC builds. Includes various sizes of Velcro straps, cable sleeves, zip ties, and cable clips. Perfect for achieving clean, organized builds with proper airflow. Kit contains enough materials for multiple builds and includes tools for professional-looking results. Great for builders, modders, or anyone wanting to improve their PC aesthetics. Price is negotiable for serious buyers. Local pickup preferred.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&auto=format&fit=crop', 80000, 'user_rob', NULL, strftime('%s','now') - 180*24*60*60),
  ('Crypto Tax Consultation', 'One-hour cryptocurrency tax consultation session with a focus on Canadian tax regulations. I help individuals understand their tax obligations related to crypto trading, mining, and other activities. Services include portfolio review, tax planning strategies, and guidance on record-keeping requirements. Perfect for crypto traders, miners, or anyone with crypto-related income. Consultation can be conducted in-person in Toronto area or remotely. Price includes follow-up email support.', 'Services', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop', 700000, 'user_rob', NULL, strftime('%s','now') - 150*24*60*60);

-- User: mika (4 listings) - Home & Garden specialist
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Home Mining Ventilation Kit', 'Complete ventilation solution for home Bitcoin mining operations. Kit includes industrial-grade ducting, high-CFM fans, sound dampening materials, and temperature monitoring equipment. Designed to maintain optimal operating temperatures while minimizing noise and heat output into living spaces. Perfect for home miners wanting to scale up their operations safely. Installation instructions included. Local pickup only due to size. Price negotiable for serious buyers.', 'Home & Garden', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1509395176047-4a66953fd231?w=1200&auto=format&fit=crop', 250000, 'user_mika', NULL, strftime('%s','now') - 200*24*60*60),
  ('USB-C Docking Station', 'CalDigit TS3 Plus Thunderbolt 3 docking station with multiple ports and 100W Power Delivery. This professional-grade dock provides 15 ports including dual DisplayPort, multiple USB ports, audio in/out, and Ethernet. Perfect for MacBook users or anyone needing a comprehensive desktop solution. Unit is in excellent condition and includes all original cables. Price is firm as this is already significantly below retail. Local pickup in Scarborough preferred.', 'Electronics', 'sell', 'Scarborough, ON', 43.7750, -79.2578, 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&auto=format&fit=crop', 800000, 'user_mika', NULL, strftime('%s','now') - 180*24*60*60),
  ('Camping Stove', 'Compact and efficient camping stove perfect for outdoor adventures. This portable stove runs on propane and provides excellent heat output for cooking. Includes carrying case and fuel adapter. Great for camping, hiking, or emergency preparedness. Stove has been lightly used and is in excellent condition. Perfect for outdoor enthusiasts or anyone needing a reliable cooking solution. Local pickup preferred. Price negotiable.', 'Sports & Outdoors', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop', 200000, 'user_mika', NULL, strftime('%s','now') - 160*24*60*60),
  ('Ultrawide 34" Monitor', 'LG 34UC88-B 34-inch ultrawide monitor with 3440x1440 resolution and 120Hz refresh rate. This curved monitor provides an immersive gaming and productivity experience. Features include FreeSync support, excellent color reproduction, and minimal bezels. Perfect for gaming, video editing, or multi-tasking. Monitor has been well-maintained in a smoke-free environment. Includes original stand and all cables. Local pickup preferred.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop', 5500000, 'user_mika', NULL, strftime('%s','now') - 140*24*60*60);

-- User: arya (4 listings) - Electronics collector
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Cold Storage Hardware Wallet (New)', 'Brand new Ledger Nano X hardware wallet in sealed box with original receipt. This premium cold storage solution provides maximum security for your cryptocurrency holdings. Features include Bluetooth connectivity, large screen, and support for over 1,800 cryptocurrencies. Perfect for serious crypto investors or anyone prioritizing security. Unit is completely sealed and unopened. Price is firm as this is already below retail. Local pickup in Toronto area preferred.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&auto=format&fit=crop', 900000, 'user_arya', NULL, strftime('%s','now') - 180*24*60*60),
  ('Gaming Chair', 'Ergonomic gaming chair with adjustable lumbar support and multiple adjustment points. Features include memory foam padding, breathable mesh back, and 4D armrests. Perfect for gamers, remote workers, or anyone spending long hours at a desk. Chair has been lightly used and is in excellent condition. Includes all adjustment tools and instructions. Local pickup preferred due to size. Price negotiable for serious buyers.', 'Home & Garden', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1515777315835-281b94c9589f?w=1200&auto=format&fit=crop', 1200000, 'user_arya', NULL, strftime('%s','now') - 160*24*60*60),
  ('Home NAS Server', 'Synology DS920+ 4-bay NAS server with 8TB of storage included. This enterprise-grade NAS provides reliable storage, backup, and media streaming capabilities. Features include dual-core processor, 4GB RAM, and support for multiple RAID configurations. Perfect for home offices, media enthusiasts, or anyone needing centralized storage. Unit has been well-maintained and includes all original accessories. Local pickup in Brampton area preferred.', 'Electronics', 'sell', 'Brampton, ON', 43.7315, -79.7624, 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=1200&auto=format&fit=crop', 18000000, 'user_arya', NULL, strftime('%s','now') - 140*24*60*60),
  ('Looking for: 1440p Monitor', 'WTB a 27-inch 1440p monitor with good color accuracy and refresh rate. Looking for models like Dell S2719DGF, LG 27GL83A-B, or similar. Monitor should be in excellent condition with no dead pixels or backlight issues. Willing to pay fair market value for quality equipment. Perfect for gaming or productivity work. Local pickup preferred in Toronto area. Please include model number and condition when responding.', 'Electronics', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop', 1200000, 'user_arya', NULL, strftime('%s','now') - 120*24*60*60);

-- User: nova (4 listings) - Sports & Hobbies
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Trading 1oz Silver Maple for sats', 'Looking to trade a 1oz Canadian Silver Maple Leaf coin for Bitcoin. Coin is in excellent condition with original mint packaging. Current spot price trade - no premium. Perfect for those wanting to diversify into precious metals or collectors looking to add to their collection. Meetup at a public place in Toronto area preferred. Will consider other locations for serious buyers. Price is firm based on current silver spot price.', 'Games & Hobbies', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop', 120000, 'user_nova', NULL, strftime('%s','now') - 150*24*60*60),
  ('Bluetooth Speakers', 'JBL Flip 5 portable Bluetooth speaker in excellent condition. This waterproof speaker provides excellent sound quality and up to 12 hours of playtime. Perfect for outdoor activities, parties, or portable audio needs. Speaker has been well-maintained and includes original charging cable. Great for music lovers or outdoor enthusiasts. Local pickup preferred. Price negotiable for serious buyers.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop', 700000, 'user_nova', NULL, strftime('%s','now') - 130*24*60*60),
  ('Looking for: Standing Desk', 'WTB a 60x30 inch standing desk with electric height adjustment. Looking for quality brands like Uplift, Jarvis, or similar. Desk should be in excellent condition with smooth operation and no damage. Willing to pay premium for quality equipment with good warranty remaining. Perfect for home office or gaming setup. Local pickup preferred in Toronto area. Please include brand, model, and condition when responding.', 'Office', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1473187983305-f615310e7daa?w=1200&auto=format&fit=crop', 800000, 'user_nova', NULL, strftime('%s','now') - 110*24*60*60),
  ('Camera Tripod', 'Lightweight aluminum camera tripod with ball head and quick-release plate. Perfect for photography, videography, or live streaming. Tripod extends to 60 inches and folds down to 20 inches for easy transport. Features include adjustable legs, center column, and carrying case. Great for photographers, content creators, or anyone needing stable camera support. Local pickup preferred. Price negotiable.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop', 250000, 'user_nova', NULL, strftime('%s','now') - 90*24*60*60);

-- User: kai (3 listings) - Budget buyer
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Mechanical Keyboard (Hot‑swap)', 'Custom mechanical keyboard with hot-swappable switches and premium keycaps. Features include RGB backlighting, aluminum case, and lubed switches for smooth operation. Perfect for gamers, programmers, or anyone appreciating quality typing experience. Keyboard has been well-maintained and includes original box and accessories. Great value for money. Local pickup preferred. Price negotiable for serious buyers.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop', 350000, 'user_kai', NULL, strftime('%s','now') - 120*24*60*60),
  ('Raspberry Pi 4 (8GB)', 'Raspberry Pi 4 Model B with 8GB RAM in excellent condition. Includes official case, power supply, and microSD card with Raspberry Pi OS pre-installed. Perfect for learning programming, home automation projects, or as a lightweight server. Board has been lightly used and is in perfect working order. Great for makers, students, or tech enthusiasts. Local pickup preferred. Price negotiable.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1581093588401-16f8b8c9f7d9?w=1200&auto=format&fit=crop', 900000, 'user_kai', NULL, strftime('%s','now') - 100*24*60*60),
  ('Looking for: Streaming Webcam', 'WTB a 1080p or better streaming webcam with good low-light performance. Looking for models like Logitech C920, Razer Kiyo, or similar. Webcam should be in excellent condition with no damage or issues. Perfect for streaming, video conferencing, or content creation. Willing to pay fair market value for quality equipment. Local pickup preferred in Toronto area. Please include model and condition when responding.', 'Electronics', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1200&auto=format&fit=crop', 150000, 'user_kai', NULL, strftime('%s','now') - 80*24*60*60);

-- User: zen (3 listings) - Office specialist
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('PS5 Disc Edition', 'Like new PlayStation 5 Disc Edition with two DualSense controllers. Console has been lightly used and is in excellent condition. Includes all original packaging, cables, and accessories. Perfect for gamers or anyone wanting to experience next-gen gaming. Console has been well-maintained in a smoke-free environment. Great value for money. Local pickup preferred due to size. Price negotiable for serious buyers.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1606813907291-76a3b2143a04?w=1200&auto=format&fit=crop', 2200000, 'user_zen', NULL, strftime('%s','now') - 100*24*60*60),
  ('Mechanical Switches Set', '90x Cherry MX Brown tactile switches, unused and in original packaging. These premium switches provide excellent tactile feedback and are perfect for custom keyboard builds. Switches are brand new and have never been soldered. Great for keyboard enthusiasts, modders, or anyone building custom mechanical keyboards. Local pickup in North York area preferred. Price is firm as this is already below retail.', 'Electronics', 'sell', 'North York, ON', 43.7615, -79.4111, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop', 300000, 'user_zen', NULL, strftime('%s','now') - 80*24*60*60),
  ('Home Office Bundle', 'Complete home office setup including desk, ergonomic chair, and adjustable desk lamp. Desk is 60x30 inches with cable management and adjustable height. Chair features mesh back and multiple adjustment points. Lamp provides adjustable brightness and color temperature. Perfect for remote workers, students, or anyone setting up a home office. Local pickup preferred due to size. Price negotiable for serious buyers.', 'Office', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1473187983305-f615310e7daa?w=1200&auto=format&fit=crop', 2500000, 'user_zen', NULL, strftime('%s','now') - 60*24*60*60);

-- User: olivia (3 listings) - Mac enthusiast
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('Looking for: MacBook Air M2', 'WTB a MacBook Air with M2 chip, preferably with 16GB RAM configuration. Looking for models in excellent condition with no damage or issues. Willing to pay premium for higher-spec models or units with AppleCare remaining. Perfect for work, school, or personal use. Local pickup preferred in Toronto area. Please include specs, condition, and any warranty information when responding.', 'Electronics', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=1200&auto=format&fit=crop', 3500000, 'user_olivia', NULL, strftime('%s','now') - 80*24*60*60),
  ('Looking for: 2TB HDD', 'WTB a 2TB hard drive for backup purposes. Looking for reliable brands like Western Digital, Seagate, or similar. Drive should be in excellent condition with no bad sectors or SMART issues. Perfect for backup storage or expanding existing systems. Willing to pay fair market value for quality equipment. Local pickup preferred in Toronto area. Please include brand, model, and condition when responding.', 'Electronics', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=1200&auto=format&fit=crop', 250000, 'user_olivia', NULL, strftime('%s','now') - 60*24*60*60),
  ('Looking for: USB Microphone', 'WTB a USB microphone suitable for podcasting or voice recording. Looking for models like Blue Yeti, Audio-Technica AT2020USB+, or similar. Microphone should be in excellent condition with no damage or issues. Perfect for content creators, podcasters, or anyone needing quality audio recording. Willing to pay fair market value for quality equipment. Local pickup preferred in Toronto area. Please include model and condition when responding.', 'Electronics', 'want', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop', 300000, 'user_olivia', NULL, strftime('%s','now') - 40*24*60*60);

-- User: noah (3 listings) - New user
INSERT INTO listings (title, description, category, ad_type, location, lat, lng, image_url, price_sat, posted_by, boosted_until, created_at) VALUES
  ('RTX 3080 10GB', 'Excellent condition RTX 3080 10GB graphics card with no mining history. Card has been used exclusively for gaming and is in perfect working order. Includes original box and all accessories. Perfect for gamers, content creators, or anyone needing high-performance graphics. Card has been well-maintained in a clean, dust-free environment. Great value for money. Local pickup preferred due to value. Price negotiable for serious buyers.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1616628188502-4047d2271797?w=1200&auto=format&fit=crop', 2800000, 'user_noah', NULL, strftime('%s','now') - 60*24*60*60),
  ('Nintendo Switch OLED', 'White Nintendo Switch OLED model in excellent condition with minimal use. Includes original box, dock, Joy-Con controllers, and all cables. Console has been well-maintained and is in perfect working order. Perfect for gamers or families looking for portable gaming. Great value for money. Local pickup preferred. Price negotiable for serious buyers.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=1200&auto=format&fit=crop', 4200000, 'user_noah', NULL, strftime('%s','now') - 50*24*60*60),
  ('Portable Power Station', 'Jackery Explorer 300 portable power station with 300Wh capacity and multiple output options. Perfect for camping, outdoor events, or emergency backup power. Features include AC outlet, USB ports, and 12V car outlet. Unit has been lightly used and is in excellent condition. Great for outdoor enthusiasts or anyone needing portable power. Local pickup preferred due to weight. Price negotiable for serious buyers.', 'Electronics', 'sell', 'Toronto, ON', 43.6532, -79.3832, 'https://images.unsplash.com/photo-1581093588401-16f8b8c9f7d9?w=1200&auto=format&fit=crop', 4500000, 'user_noah', NULL, strftime('%s','now') - 30*24*60*60);

-- Verify seeding results
SELECT 'Users seeded:' as info, COUNT(*) as count FROM users
UNION ALL
SELECT 'Listings seeded:', COUNT(*) FROM listings
UNION ALL
SELECT 'Listings per user (avg):', ROUND(CAST(COUNT(*) AS FLOAT) / (SELECT COUNT(*) FROM users), 2) FROM listings;
